version: '3.8'

networks:
  default:
    external: true
    name: apps-network

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password    
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpress
      DB_TZ: $DB_TZ

    volumes:
      - ./data/dbdata:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./data/wordpress:/var/www/html

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8992:80"
    volumes:
      - ./data/wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./data/certbot-etc:/etc/letsencrypt

  # certbot:
  #   depends_on:
  #     - webserver
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./data/certbot-etc:/etc/letsencrypt
  #     - ./data/wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email amit@khare.co.in --agree-tos --no-eff-email --staging -d khabar91.in -d www.khabar91.in
